export enum Scenes {
    REMIND_TASK_SCENE = 'REMIND_TASK_SCENE',
    SUBSCRRIBE_SCENE = 'SUBSCRRIBE_SCENE',
    SUGGEST_SCENE = 'SUGGEST_SCENE',
    WEATHER_SCENE = 'WEATHER_SCENE',
    ADD_TASK_SCENE = 'ADD_TASK_SCENE',
}
